### ISSUE TITLE
Cannot reply without permission to read message history

### ISSUE THREAD

**Issue by ApolloRoboto** [Apollo-Roboto/discord-pokeguess#1]
Error while trying to reply with the CloseAnswerEmbed.

The bot should instead warn that it cannot send help messages without extra permissions.

```log
2023-04-28 19:14:26 INFO    controllers.guess         Interaction: pokeguess, generation: Choice(name='Generation 1', value=1), timeout: 60
2023-04-28 19:14:26 INFO    services.guesser_service  Searching for pokemon #128 in the file system
2023-04-28 19:14:26 INFO    services.guesser_service  Creating a guesser for pokemon #128 in channel 1097515446883860500
2023-04-28 19:14:26 INFO    controllers.guess         Sending HiddenEmbed
2023-04-28 19:14:33 INFO    controllers.guess         User 347507564545835009 almost got it
2023-04-28 19:14:33 INFO    controllers.guess         Sending CloseAnswerEmbed
2023-04-28 19:14:33 ERROR   discord.client            Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/app/src/controllers/guess_controller.py", line 328, in on_message
    await message.reply(embed=embed)
  File "/usr/local/lib/python3.10/site-packages/discord/message.py", line 1246, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 160002): Cannot reply without permission to read message history
2023-04-28 19:15:27 INFO    services.guesser_service  Ending guesser for pokemon #128 in channel 1097515446883860500
2023-04-28 19:15:27 INFO    services.guesser_service  Users lost
2023-04-28 19:15:27 INFO    controllers.guess         Sending RevealedEmbed
```

**Comment by Apollo-Roboto** [comment]
Similarly, missing correct permissions to send the game result.
```log
2023-08-12 16:18:49 INFO    controllers.guess         Interaction: pokeguess, generation: None, timeout: 60
2023-08-12 16:18:49 INFO    services.guesser_service  Searching for pokemon #778 in the file system
2023-08-12 16:18:49 INFO    services.guesser_service  Creating a guesser for pokemon #778 in channel 1139951798157840486
2023-08-12 16:18:49 INFO    controllers.guess         Sending HiddenEmbed
2023-08-12 16:18:53 INFO    services.guesser_service  Ending guesser for pokemon #778 in channel 1139951798157840486
2023-08-12 16:18:53 INFO    services.guesser_service  User 629036549430050816 won
2023-08-12 16:18:53 INFO    controllers.guess         Sending RevealedEmbed
2023-08-12 16:18:53 ERROR   services.guesser_service  Unhandled exception while calling on_guesser_end_event
Traceback (most recent call last):
  File "/app/src/services/guesser_service.py", line 89, in end_guesser
    await event(guesser)
  File "/app/src/controllers/guess_controller.py", line 338, in on_guess_end
    await guesser.channel.send(embed=embed, file=file)
  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
