### ISSUE TITLE
Can't send messages in private threads

### ISSUE THREAD

**Issue by Apollo-Roboto** [Apollo-Roboto/discord-pokeguess#2]
Can't send messages in private threads.

Should probably send an error to the user instead.

```log
2023-06-26 21:25:30 INFO    controllers.guess         Sending RevealedEmbed
2023-06-26 21:25:31 ERROR   services.guesser_service  Unhandled exception while calling on_guesser_end_event
Traceback (most recent call last):
  File "/app/src/services/guesser_service.py", line 89, in end_guesser
    await event(guesser)
  File "/app/src/controllers/guess_controller.py", line 338, in on_guess_end
    await guesser.channel.send(embed=embed, file=file)
  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by Apollo-Roboto** [comment]
and private messages too
